version: "3.9"

services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./app:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge