version: "3.9"

services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./app:/app
    networks:
      - app-network


  redis:
    image: "redis:alpine"
    container_name: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge