version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge